const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
  ...[
  "The Accountant", "The Accountant 2", "A Working Man", "Companion", "Mickey 17", "Novocaine", "Heart Eyes", "Nosferatu", "Longlegs", "Speak No Evil", "Trap", "Blink Twice", "Twisters", "Fly Me to the Moon", "IF", "The Instigators", "Hit Man", "A Real Pain", "Challengers", "Conclave", "Emilia Perez", "Saturday Night", "Alien: Romulus", "Kingdom of the Planet of the Apes", "Furiosa: A Mad Max Saga", "The Garfield Movie", "Ghostbusters: Frozen Empire", "Kingdom Come", "Migration", "Wish", "Elemental", "Napoleon", "The Marvels", "Blue Beetle", "The Flash", "Shazam! Fury of the Gods", "Creed III", "65", "Operation Fortune: Ruse de Guerre", "Missing", "Evil Dead Rise", "Renfield", "The Boogeyman", "Cobweb", "No One Will Save You", "Love and Monsters", "Violent Night", "The Pale Blue Eye", "Where the Crawdads Sing", "Ticket to Paradise", "Elvis", "BlackBerry", "AIR", "The Creator", "Dungeons & Dragons: Honor Among Thieves", "The Covenant", "Joy Ride", "Asteroid City", "Past Lives", "The Iron Claw", "The Killer", "Leave the World Behind", "Maestro", "The Burial", "The Color Purple", "A Haunting in Venice", "The Equalizer 3", "Gran Turismo", "Beau Is Afraid", "Strays", "Bottoms", "Lisa Frankenstein", "Anyone But You", "The Bike Riders", "The Order", "Here", "Juror #2", "The Apprentice", "We Live in Time", "Lee", "Carry-On", "Back in Action", "Rebel Ridge", "Unfrosted", "The Ministry of Ungentlemanly Warfare", "The Watchers", "The Strangers: Chapter 1", "Abigail", "Imaginary", "Ordinary Angels", "Arthur the King", "The Forge", "Small Things Like These", "The Fire Inside", "Wicked", "Moana 2", "Inside Out 2", "Deadpool & Wolverine", "Gladiator II", "Beetlejuice Beetlejuice"
],
...[
  "The Intern", "The Intern's Guide to Love", "The Impossible", "The Impossible Heist", "The Illusionist", "The Judge", "The Kingdom", "The Lincoln Lawyer", "The Losers", "The Mechanic", "The Monuments Men", "The Mule", "The Other Woman", "The Place Beyond the Pines", "The Rite", "The Rundown", "The Sea Beast", "The Sisters Brothers", "The Sorcerer's Apprentice", "The Spy Next Door", "The Tourist", "The Transporter Refueled", "The Visit", "The Walk", "The Way Back", "The Wedding Ringer", "This Is the End", "Three Thousand Years of Longing", "Tinker Tailor Soldier Spy", "Tomorrowland", "Tower Heist", "Triple 9", "Triple Frontier", "Trolls", "Trolls World Tour", "Trolls Band Together", "Turbo", "Unhinged", "Unknown", "Valerian and the City of a Thousand Planets", "Valkyrie", "Vantage Point", "War for the Planet of the Apes", "Warm Bodies", "We're the Millers", "What Happened to Monday", "White Boy Rick", "Why Him?", "Without Remorse", "Wonder Park", "World Trade Center", "X", "Pearl", "MaXXXine", "Yes Day", "You People", "Your Place or Mine", "Zathura", "Zero Dark Thirty", "Zombieland: Double Tap", "The Age of Adaline", "The Best of Me", "The Book of Eli", "The Boy", "The Butler", "The Campaign", "The Change-Up", "The Courier", "The Death of Stalin", "The Eagle", "The Finest Hours", "The Foreigner", "The Girl on the Train", "The Great Wall", "The Grey", "The Impossible", "The Last King of Scotland", "The Longest Ride", "The Lucky One", "The November Man", "The Peanut Butter Falcon", "The Promise", "The Rhythm Section", "The Spy Who Dumped Me", "The Upside", "The Voyeurs", "Three Identical Strangers", "Till", "Togo", "Uncut Gems", "War Dogs", "White Noise", "Wish I Was Here", "Yesterday", "Young Adult", "Zero Dark Thirty"
],
...[
  "28 Years Later", "A Minecraft Movie", "A Quiet Place: Day One", "Aftersun", "All of Us Strangers", "Amsterdam", "Anora", "Anyone but You", "Babygirl", "Bad Times at the El Royale", "Ballerina", "Beasts of the Southern Wild", "Belfast", "Big Eyes", "Birds of Prey", "Black Bag", "Black Phone", "BlackBerry", "Blonde", "Bones and All", "Booksmart", "Breathe", "Bridge of Spies", "Bros", "Burnt", "Captain Fantastic", "Cha Cha Real Smooth", "Cocaine Bear", "Code 8", "Code 8: Part II", "Collateral Beauty", "Creed II", "Cruella", "Daddio", "Damsel", "Deepwater Horizon", "Detroit", "Don't Move", "Drive-Away Dolls", "Dumb Money", "Eileen", "Emily the Criminal", "Ender's Game", "Everything Must Go", "Fair Play", "Fall", "Father Stu", "Fences", "Finestkind", "First Man", "Five Feet Apart", "Foe", "Fresh", "Glass Onion: A Knives Out Mystery", "Green Room", "Greyhound", "Guy Ritchie's The Covenant", "Harold and the Purple Crayon", "Heretic", "Hidden Figures", "Horizon: An American Saga – Chapter 1", "Horizon: An American Saga – Chapter 2", "Hustlers", "I Care a Lot", "I Saw the TV Glow", "IF", "In the Heart of the Sea", "In a Violent Nature", "Indiana Jones and the Dial of Destiny", "Infinite", "Inheritance", "Jackpot!", "Jerry & Marge Go Large", "Joy", "Jungleland", "Kate", "King Arthur: Legend of the Sword", "Late Night", "Living", "Love Lies Bleeding", "Luck", "Lyle, Lyle, Crocodile", "M3GAN", "Ma", "Mank", "Marlowe", "May December", "Memory", "Minari", "No Exit", "No Sudden Move", "No Strings Attached", "Nyad", "One Life", "One of Them Days", "Our Friend", "Pain Hustlers", "Parallel Mothers"
],
...[
  "2012", "9 to 5", "Act of Valor", "Alexander and the Terrible, Horrible, No Good, Very Bad Day", "Alice Through the Looking Glass", "All the Bright Places", "Alpha", "Annabelle", "Annabelle: Creation", "Annabelle Comes Home", "Anon", "Aquamarine", "Are We There Yet?", "Arthur the King", "Battle Los Angeles", "Battleship", "Beast", "Beauty Shop", "Beowulf", "Big Fish", "Billy Lynn's Long Halftime Walk", "Bridge to Terabithia", "Bulletproof Monk", "Burlesque", "Cake", "Captain Underpants: The First Epic Movie", "Cats", "Central Intelligence", "Chaos Walking", "Chevalier", "CHiPs", "Cinderella Man", "Click", "Cloverfield", "Cowboys & Aliens", "Crawl", "Creed", "Cry Macho", "Daddy Day Care", "Daddy's Little Girls", "Date Night", "Death at a Funeral", "Death Wish", "Deep Blue Sea 2", "Deep Blue Sea 3", "Duplicity", "Earth to Echo", "Eat Pray Love", "Eight Legged Freaks", "Ella Enchanted", "Enemy of the State", "Escape from Planet Earth", "Extraction", "Extraction 2", "Fantastic Four", "Fantastic Four: Rise of the Silver Surfer", "Fantastic Four", "Final Score", "Flight of the Phoenix", "Fools Gold", "Forever My Girl", "Fracture", "Freaky", "Geostorm", "Ghost Ship", "Ghosted", "Gifted", "Greenland", "Happy Death Day", "Happy Death Day 2U", "Hardcore Henry", "Haunted Mansion", "Hell Fest", "Hitch", "Hop", "Host", "House at the End of the Street", "Identity Thief", "Inglourious Basterds", "Insidious: The Red Door", "Into the Forest", "Journey's End", "Jumper", "Jupiter Ascending", "Just Friends", "Kate", "Knowing", "Last Christmas", "Legend of the Guardians: The Owls of Ga'Hoole", "Life as We Know It", "Love Hurts", "Max Payne", "Meet Dave", "Mile 22", "Mirror Mirror", "Monster Trucks"
],
...[
  "The Incredible Burt Wonderstone", "The Last Voyage of the Demeter", "The Paperboy", "The Perfect Storm", "The Possession", "The Princess and the Frog", "The Protege", "The Punisher", "The Punisher: War Zone", "The Rental", "The Return", "The School for Good and Evil", "The Secret in Their Eyes", "The Skeleton Key", "The Space Between Us", "The Spy", "The Sum of All Fears", "The Taking of Pelham 123", "The Talented Mr. Ripley", "The Tax Collector", "The Texas Chainsaw Massacre", "The Texas Chainsaw Massacre: The Beginning", "Texas Chainsaw 3D", "Leatherface", "Texas Chainsaw", "The Time Traveler's Wife", "The Uninvited", "The Vigil", "The Void", "The War with Grandpa", "The Water Diviner", "The Wedding Planner", "The Whole Truth", "The Woman in the Window", "The Words", "Thirteen Days", "Thirteen Lives", "This Means War", "Three Kings", "Tigerland", "Timeline", "Titanic II", "Tom & Jerry", "Tommy Boy", "Torque", "Traffic", "Trainwreck", "Transcendence", "Transporter 2", "Transporter 3", "Transporter", "Triangle", "Troll Hunter", "Troll Hunters: Rise of the Titans", "True Story", "Truth", "Tusk", "Tyler Perry's Madea's Witness Protection", "Tyler Perry's Boo! A Madea Halloween", "Tyler Perry's Boo 2! A Madea Halloween", "Uncle Drew", "Underdog", "Underwater", "Undisputed", "Undisputed II: Last Man Standing", "Undisputed III: Redemption", "Universal Soldier: Day of Reckoning", "Vacation Friends", "Vacation Friends 2", "Vertical Limit", "VFW", "Virus", "Vivarium", "Voyagers", "Waiting...", "War Room", "War on Everyone", "Warrior's Way", "Welcome to Marwen", "What Men Want", "When the Game Stands Tall", "Where Eagles Dare", "White House Farm", "White Oleander", "Wild Hogs", "Wild Robot", "Windtalkers", "Winter's Bone", "Without a Paddle", "Wonder Wheel", "Words on Bathroom Walls", "Wrong Turn", "Wrong Turn 2: Dead End", "Wrong Turn 3: Left for Dead", "Wrong Turn 4: Bloody Beginnings", "Wrong Turn 5: Bloodlines", "Wrong Turn 6: Last Resort", "Wrong Turn"
],
...[
  "127 Hours", "1408", "17 Again", "21 Bridges", "22 Bullets", "30 Minutes or Less", "47 Meters Down", "47 Meters Down: Uncaged", "500 Days of Summer", "A Dog's Purpose", "A Dog's Journey", "A Man Called Otto", "A Monster Calls", "A Walk Among the Tombstones", "Accepted", "Across the Universe", "After the Sunset", "All Eyez on Me", "American Animals", "American Honey", "Anger Management", "Anonymous", "Arctic", "Armored", "Assault on Precinct 13", "August Osage County", "Bad Education", "Bad Moms", "Bad Moms Christmas", "Bandidas", "Barbarian", "Be Kind Rewind", "Beautiful Creatures", "Before We Go", "Begin Again", "Belle", "Ben Is Back", "Big George Foreman", "Black and Blue", "Bleed for This", "Blue Story", "Body Cam", "Boiler Room", "Book Club", "Boss Level", "Bridge to Terabithia", "Brittany Runs a Marathon", "Brooklyn's Finest", "Brothers Grimm", "Burn After Reading", "Burning", "Cake", "Can You Ever Forgive Me?", "Captain Fantastic", "Cell", "Centurion", "Champions", "Changeling", "Chasing Mavericks", "Children of Men", "Chronicles of Riddick", "City of Ember", "Cloudy with a Chance of Meatballs 2", "Coach", "Cold Pursuit", "Collateral Damage", "Come Play", "Confessions of a Teenage Drama Queen", "Contagion", "Copshop", "Countdown", "Cursed", "Dark Skies", "Death Sentence", "Deep Rising", "Deliverance Creek", "Detroit Rock City", "Dirty Grandpa", "Disturbing Behavior", "Dog Soldiers", "Downsizing", "Dream House", "Drive Angry", "Dredd", "Drillbit Taylor", "Eddie the Eagle", "Elizabethtown", "Empire of Light", "Ender's Game", "Enemy Mine", "Escape from Pretoria", "Europa Report", "Extraordinary Measures", "Fall", "Fear Street Part One: 1994", "Fear Street Part Two: 1978", "Fear Street Part Three: 1666"
],
...[
  "28 Weeks Later", "Abduction", "Abominable", "About Time", "Accepted", "Allied", "American Made", "American Sniper", "Angels & Demons", "Another Simple Favor", "Aquaman", "Aquaman and the Lost Kingdom", "Arthur Christmas", "As Above, So Below", "Bad Boys for Life", "Bad Boys: Ride or Die", "Ballistic: Ecks vs. Sever", "Band Slam", "Battle: Los Angeles", "Beautiful Boy", "Becoming Jane", "Bee Movie", "Before I Fall", "Ben 10: Race Against Time", "Ben 10: Alien Swarm", "Big Hero 6", "Black Adam", "Blood Father", "Blue Crush", "Bridge of Spies", "Broken City", "Bulletproof", "Camp Rock", "Camp Rock 2: The Final Jam", "Captain Phillips", "Cars", "Cars 2", "Cars 3", "Charlie and the Chocolate Factory", "Cheaper by the Dozen", "Chicken Little", "Cloud Atlas", "Cloudy with a Chance of Meatballs", "Constantine", "Coraline", "Cowboys & Aliens", "Daddy's Home", "Daddy's Home 2", "Daredevil", "Date Night", "Deep Impact", "Diary of a Mad Black Woman", "Divergent", "Insurgent", "Allegiant", "Doctor Sleep", "Dragonball Evolution", "Dream Scenario", "Due Date", "Eagle Eye", "Earth", "Edge of Tomorrow", "Epic", "Escape Plan", "Escape Plan 2: Hades", "Escape Plan: The Extractors", "Fantastic Mr. Fox", "Fast X", "Finding Dory", "Five Nights at Freddy's", "Flight", "Focus", "Freaky Friday", "Fury", "G-Force", "Gangster Squad", "Get Out", "Ghost Rider", "Ghost Rider: Spirit of Vengeance", "Gone Girl", "Goosebumps", "Goosebumps 2: Haunted Halloween", "Green Book", "Happy Feet", "Happy Feet Two", "Hercules", "Home", "Home Alone", "Home Alone 2: Lost in New York", "Home Alone 3", "Home Alone 4", "Home Alone: The Holiday Heist", "Home Sweet Home Alone", "Horton Hears a Who!", "How Do You Know", "Ice Princess", "Identity Theft"
],
...[
  "I, Tonya", "Ice Cube", "Idiocracy", "Igor", "Imagine That", "Immaculate", "In Her Shoes", "In the Heights", "Inkheart", "Inside Man", "Into the Woods", "Invincible", "It Comes at Night", "Jack and Jill", "Jack the Giant Slayer", "Jeepers Creepers", "Jeepers Creepers 2", "Jeepers Creepers: Reborn", "John Tucker Must Die", "Journey to Bethlehem", "Jumanji: The Next Level", "Jungle", "Justice League: Crisis on Infinite Earths", "Kate & Leopold", "Kicking & Screaming", "Killers", "King Arthur", "Kingdom of Heaven", "Kubo and the Two Strings", "Land of Bad", "Last Seen Alive", "Leap!", "Legend", "Letters to Juliet", "Liar Liar", "Life After Beth", "Lights Out", "Little", "Little Monsters", "Living with the Enemy", "Logan Lucky", "Love and Other Drugs", "Love, Rosie", "Loving", "M3GAN 2.0", "MacGruber", "Mad Money", "Max Steel", "Maze Runner: The Death Cure", "Maze Runner: The Scorch Trials", "Me Time", "Mean Girls", "Meg 2: The Trench", "Men", "Midnight Special", "Million Dollar Baby", "Minions: The Rise of Gru", "Monster House", "Morbius", "Mother!", "Mr. Peabody & Sherman", "Mummies", "My Spy", "My Spy: The Eternal City", "My Sister's Keeper", "Nerve", "Next Goal Wins", "Nightbooks", "No Good Deed", "Nocturnal Animals", "Nothing But the Truth", "Oldboy", "One Hour Photo", "One Missed Call", "Only the Brave", "Open Range", "Operation Mincemeat", "Orion and the Dark", "Out of the Furnace", "Panic", "Paul Blart: Mall Cop", "Paul Blart: Mall Cop 2", "Paycheck", "Percy Jackson: Sea of Monsters", "Pet", "Playing with Fire", "Pride and Glory", "Project Almanac", "Project X", "Queen of Katwe", "Rabbit Hole", "Rango", "Red Eye", "Remember Me", "Ride Along", "Ride Along 2", "Robin Hood"
]
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  if (currentArray.length <= 5) {
    currentArray = [];
  }
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "0: { code: 'english_movies', name: 'English Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} English movies (added third huge batch).`);
} else {
  console.log("Could not find the english_movies section.");
}
