const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
  ...[
  "The Revenant", "The Ring", "The Ring Two", "The Road", "The Rock", "The Santa Clause", "The Santa Clause 2", "The Santa Clause 3: The Escape Clause", "The Secret Garden", "The Secret Life of Pets", "The Secret Life of Pets 2", "The Secret World of Arrietty", "The Shape of Water", "The Shawshank Redemption", "The Shining", "The Sixth Sense", "The Smurfs", "The Smurfs 2", "The Social Network", "The SpongeBob Movie: Sponge Out of Water", "The SpongeBob SquarePants Movie", "The SpongeBob Movie: Sponge on the Run", "The Super Mario Bros. Movie", "The Terminal", "The Thing", "The Thomas Crown Affair", "The Three Musketeers", "The Tomorrow War", "The Town", "The Truman Show", "The Tuxedo", "The Twilight Saga: Twilight", "The Twilight Saga: New Moon", "The Twilight Saga: Eclipse", "The Twilight Saga: Breaking Dawn – Part 1", "The Twilight Saga: Breaking Dawn – Part 2", "The Unbearable Weight of Massive Talent", "The Unforgivable", "The Untouchables", "The Usual Suspects", "The Visit", "The Wall", "The Watch", "The Waterboy", "The Whale", "The Wolf of Wall Street", "The Wolverine", "The Woman in Black", "The Woman King", "The World's End", "Thelma & Louise", "There Will Be Blood", "Thor", "Thor: The Dark World", "Thor: Ragnarok", "Thor: Love and Thunder", "Three Billboards Outside Ebbing, Missouri", "Thunderbolts*", "Thunderstruck", "Titan A.E.", "Titanic", "Tomb Raider", "Top Gun", "Top Gun: Maverick", "Total Recall", "Toy Story", "Toy Story 2", "Toy Story 3", "Toy Story 4", "Training Day", "Transformers", "Transformers: Revenge of the Fallen", "Transformers: Dark of the Moon", "Transformers: Age of Extinction", "Transformers: The Last Knight", "Transformers: Rise of the Beasts", "Treasure Planet", "Tremors", "Tropic Thunder", "Tron", "TRON: Legacy", "True Grit", "True Lies", "Troy", "Turning Red", "Twister", "Twisters", "Unbreakable", "Uncharted", "Uncut Gems", "Underworld", "Underworld: Evolution", "Underworld: Rise of the Lycans", "Unstoppable", "Up", "Us", "Vacation", "Van Helsing", "Venom", "Venom: Let There Be Carnage"
],
...[
  "Vertigo", "V for Vendetta", "Vice", "Vicky Cristina Barcelona", "Violent Night", "War Horse", "War of the Worlds", "Warcraft", "War Dogs", "WarGames", "Warrior", "Watchmen", "We Bought a Zoo", "Wedding Crashers", "West Side Story", "What Women Want", "Whiplash", "White Chicks", "White House Down", "Who Framed Roger Rabbit", "Willy Wonka & the Chocolate Factory", "Wind River", "Witness", "Wonder", "Wonder Woman", "Wonder Woman 1984", "Wonka", "World War Z", "Wrath of Man", "Wreck-It Ralph", "Ralph Breaks the Internet", "X-Men", "X2", "X-Men: The Last Stand", "X-Men Origins: Wolverine", "X-Men: First Class", "The Wolverine", "X-Men: Days of Future Past", "X-Men: Apocalypse", "Logan", "Dark Phoenix", "X-Men: Dark Phoenix", "X-Men: New Mutants", "xXx", "xXx: State of the Union", "xXx: Return of Xander Cage", "Yesterday", "Yes Man", "You Don't Mess with the Zohan", "You Were Never Really Here", "You've Got Mail", "Young Guns", "Young Guns II", "Zack Snyder's Justice League", "Zathura: A Space Adventure", "Zero Dark Thirty", "Zodiac", "Zombieland", "Zombieland: Double Tap", "Zootopia", "13 Hours: The Secret Soldiers of Benghazi", "16 Blocks", "30 Days of Night", "40 Days and 40 Nights", "42", "50 First Dates", "55 Steps", "61*", "65", "8 Mile", "9", "A Christmas Carol", "A Good Day to Die Hard", "A History of Violence", "A Million Ways to Die in the West", "A Most Wanted Man", "A Nightmare on Elm Street", "A Perfect Getaway", "A River Runs Through It", "A Series of Unfortunate Events", "A Simple Favor", "A Time to Kill", "Accepted", "Acts of Valor", "Ad Astra", "Adventureland", "After", "After We Collided", "After We Fell", "After Ever Happy", "Alexander", "Alvin and the Chipmunks", "Alvin and the Chipmunks: The Squeakquel", "Alvin and the Chipmunks: Chipwrecked", "Alvin and the Chipmunks: The Road Chip", "Ambulance", "American Assassin", "American Reunion", "American Wedding"
],
...[
  "American Ultra", "American Wedding", "Amistad", "Analyze This", "Analyze That", "Anastasia", "Anna", "Anna and the King", "Any Given Sunday", "Apocalypto", "Arachnophobia", "Around the World in 80 Days", "Arthur", "Artificial Intelligence: AI", "August Rush", "Austin Powers: International Man of Mystery", "Austin Powers: The Spy Who Shagged Me", "Austin Powers in Goldmember", "Babe", "Babe: Pig in the City", "Baby Driver", "Baby's Day Out", "Bad Grandpa", "Bad Santa", "Bad Santa 2", "Balls of Fury", "Bandits", "Bang the Drum Slowly", "Basic", "Basic Instinct", "Be Cool", "Beauty and the Beast", "Because I Said So", "Bedtime Stories", "Behind Enemy Lines", "Being John Malkovich", "Beloved", "Ben-Hur", "Bend It Like Beckham", "Beverly Hills Cop", "Beverly Hills Cop II", "Beverly Hills Cop III", "Beverly Hills Cop: Axel F", "Big Daddy", "Billy Elliot", "Billy Madison", "Black Mass", "Black Swan", "BlacKkKlansman", "Blast from the Past", "Blood Diamond", "Bloodshot", "Blue Jasmine", "Blue Velvet", "Body of Lies", "Bodyguard", "Bonnie and Clyde", "Borat", "Borat Subsequent Moviefilm", "Born on the Fourth of July", "Bottle Rocket", "Bowfinger", "Brain on Fire", "Breakdown", "Brick", "Bridesmaids", "Bright", "Bring It On", "Broken Arrow", "Brooklyn", "Brother Bear", "Brothers", "Bruce Lee: Dragon", "Bug", "Buried", "Burlesque", "Cadillac Records", "Cape Fear", "Carlito's Way", "Carnage", "Carol", "Cellular", "Changing Lanes", "Chappie", "Cheaper by the Dozen", "Cheaper by the Dozen 2", "Chicken Run", "Children of Heaven", "Chronicle", "Cinderella Man", "City of Angels", "City Slickers", "Clear and Present Danger", "Clerks", "Closer", "Coach Carter", "Cold Mountain", "Collateral Beauty", "Colombiana", "Coneheads", "Confessions of a Shopaholic"
],
...[
  "Confessions of a Dangerous Mind", "Congo", "Cowboys & Aliens", "Crank", "Crank: High Voltage", "Crimson Tide", "Crocodile Dundee", "Crocodile Dundee II", "Cube", "Cujo", "Cyrano", "Dark Shadows", "Date Movie", "Daybreakers", "Days of Thunder", "Death Becomes Her", "Death Race", "Death Race 2", "Deepwater Horizon", "Defiance", "Deliver Us from Evil", "Demolition Man", "Dennis the Menace", "Deja Vu", "Detroit", "Devil", "Diary of a Wimpy Kid", "Diary of a Wimpy Kid: Rodrick Rules", "Diary of a Wimpy Kid: Dog Days", "Diary of a Wimpy Kid: The Long Haul", "Dick Tracy", "Disturbia", "Dolittle", "Domino", "Don Jon", "Donnie Brasco", "Donnie Darko", "Downfall", "Downsizing", "Dragonheart", "Dreamgirls", "Due Date", "Dungeons & Dragons", "Dungeons & Dragons: Honor Among Thieves", "Eagle Eye", "Easy A", "Eight Below", "Elizabeth", "Elizabeth: The Golden Age", "End of Watch", "Enemy", "Entrapment", "Eragon", "Erin Brockovich", "Escape Room", "Escape Room: Tournament of Champions", "Evan Almighty", "Event Horizon", "Ever After", "Extremely Wicked, Shockingly Evil and Vile", "Failure to Launch", "Falling Down", "Fantastic Voyage", "Far and Away", "Fatal Attraction", "Father of the Bride", "Father of the Bride Part II", "Fear", "Field of Dreams", "Final Destination", "Final Destination 2", "Final Destination 3", "The Final Destination", "Final Destination 5", "Fireproof", "First Knight", "Fist of Fury", "Flash Gordon", "Flicka", "Flightplan", "Fools Rush In", "Footloose", "Four Weddings and a Funeral", "Frequency", "From Dusk Till Dawn", "Frost/Nixon", "Full Metal Jacket", "Funny People", "G.I. Jane", "G.I. Joe: The Rise of Cobra", "G.I. Joe: Retaliation", "Galaxy Quest", "Geostorm", "Get Smart", "Girl, Interrupted", "Glory", "Gods of Egypt", "Gone Baby Gone", "Good Boys", "Grease"
],
...[
  "Green Zone", "Grindhouse", "Grumpy Old Men", "Grumpier Old Men", "Hackers", "Hall Pass", "Halloween", "Halloween II", "Halloween H20: 20 Years Later", "Halloween: Resurrection", "Halloween", "Halloween Kills", "Halloween Ends", "Harold & Kumar Go to White Castle", "Harold & Kumar Escape from Guantanamo Bay", "A Very Harold & Kumar Christmas", "Harriet", "Harriet the Spy", "Hellboy", "Hellboy II: The Golden Army", "Hellboy", "Hellraiser", "Hellraiser II: Hellbound", "Hellraiser III: Hell on Earth", "Herbie: Fully Loaded", "Hereditary", "Hidalgo", "High Fidelity", "High School Musical", "High School Musical 2", "High School Musical 3: Senior Year", "Hitman", "Hitman: Agent 47", "Holes", "Hollow Man", "Horrible Bosses", "Horrible Bosses 2", "Hostel", "Hostel: Part II", "Hot Fuzz", "Hot Rod", "Hotel Rwanda", "House of Gucci", "House of Wax", "How High", "How the Grinch Stole Christmas", "How to Lose a Guy in 10 Days", "Hustle", "I Am Number Four", "I Care a Lot", "I Know What You Did Last Summer", "I Still Know What You Did Last Summer", "I Love You, Man", "I Now Pronounce You Chuck & Larry", "I Origins", "I Spy", "I Still Believe", "If", "Imaginary", "Immortals", "Inferno", "Insomnia", "Instant Family", "Into the Blue", "Into the Woods", "Ip Man", "Isle of Dogs", "Jack", "Jack Frost", "Jackass: The Movie", "Jackass Number Two", "Jackass 3D", "Jackass Forever", "Jersey Girl", "John Q", "Johnny English", "Johnny English Reborn", "Johnny English Strikes Again", "Johnny Mnemonic", "Joker", "Judas and the Black Messiah", "Julie & Julia", "Juno", "Just Go with It", "Just Like Heaven", "Just Mercy", "Keeping the Faith", "Kickboxer", "Kingdom of Heaven", "Kiss Kiss Bang Bang", "Kong: Skull Island", "Kramer vs. Kramer", "Krampus", "L.A. Confidential", "Ladder 49", "Land of the Lost", "Last Holiday", "Legally Blonde"
],
...[
  "Legally Blonde 2: Red, White & Blonde", "Lemony Snicket's A Series of Unfortunate Events", "Letters from Iwo Jima", "License to Wed", "Lilo & Stitch", "Limitless", "Lions for Lambs", "Little Fockers", "Little Giants", "Little Women", "Live Free or Die Hard", "Locke", "London Has Fallen", "Lone Survivor", "Lone Wolf McQuade", "Long Shot", "Look Who's Talking", "Look Who's Talking Too", "Look Who's Talking Now", "Looper", "Lost in Space", "Love & Basketball", "Love and Monsters", "Love, Simon", "Madame Web", "Magic Mike", "Magic Mike XXL", "Magnolia", "Major League", "Major League II", "Malcolm X", "Mank", "Max", "Me Before You", "Me, Myself & Irene", "Mechanic: Resurrection", "Meet Joe Black", "Memoirs of a Geisha", "Michael", "Michael Clayton", "Michael Collins", "Midnight Run", "Midway", "Milk", "Miracle", "Misery", "Miss Congeniality", "Miss Congeniality 2: Armed and Fabulous", "Miss Peregrine's Home for Peculiar Children", "Miss Sloane", "Moneyball", "Monkeybone", "Monte Carlo", "Monster", "Monster-in-Law", "Moonlight", "Moonraker", "Mortal Engines", "Mouse Hunt", "Mr. Deeds", "Mr. Nobody", "Mr. Popper's Penguins", "Much Ado About Nothing", "Mud", "Mulan", "Mulholland Drive", "Munich", "Music and Lyrics", "Mystic River", "Nanny McPhee", "Nanny McPhee Returns", "Napoleon", "National Lampoon's Christmas Vacation", "Need for Speed", "Never Back Down", "Never Been Kissed", "News of the World", "Next", "Nick of Time", "Night School", "Nim's Island", "Nixon", "Nobody's Fool", "No Escape", "North", "Nothing to Lose", "One Fine Day", "Only the Brave", "Outbreak", "Outlander", "Over the Hedge", "Overboard", "Overlord", "P.S. I Love You", "Paddington in Peru", "Palm Springs", "Patriot Games", "Pay It Forward", "Payback"
],
...[
  "Sinners", "The Fall", "The Northman", "The Green Knight", "The Covenant", "The Creator", "Civil War", "Monkey Man", "Bullet Bullet Train", "The Beekeeper", "Plane", "The Ministry of Ungentlemanly Warfare", "Argylle", "The Ministry of Ungentlemanly Warfare", "Gran Turismo", "The Boy and the Heron", "The Holdovers", "Killers of the Flower Moon", "Poor Things", "The Banshees of Inisherin", "Everything Everywhere All at Once", "The Whale", "Babylon", "The Menu", "The Fabelmans", "Women Talking", "The North Water", "The Outfit", "The Black Phone", "No Exit", "The Gray Man", "The Unbearable Weight of Massive Talent", "Bullet Train", "Ambulance", "Dog", "The Lost City", "The Woman King", "Devotion", "The Outfit", "Licorice Pizza", "King Richard", "Nightmare Alley", "Last Night in Soho", "Spencer", "The Last Duel", "Free Guy", "Nobody", "The Suicide Squad", "Don't Worry Darling", "The Forever Purge", "Old", "Finch", "Those Who Wish Me Dead", "Cherry", "The Tomorrow War", "The Harder They Fall", "The Last Letter from Your Lover", "Greyhound", "News of the World", "The Call of the Wild", "Tenet", "Palm Springs", "The Invisible Man", "The Trial of the Chicago 7", "Sound of Metal", "Soul", "The Gentlemen", "1917", "Ford v Ferrari", "Jojo Rabbit", "Knives Out", "Rocketman", "Ad Astra", "Dark Waters", "Richard Jewell", "A Star Is Born", "Ready or Not", "Searching", "Upgrade", "Vice", "Widows", "Game Night", "Hostiles", "Wind River", "Baby Driver", "The Big Sick", "Molly's Game", "The Post", "Atomic Blonde", "The Founder", "Hell or High Water", "Hidden Figures", "Arrival", "Hacksaw Ridge", "Manchester by the Sea", "The Nice Guys", "Creed", "The Martian", "Straight Outta Compton", "Room", "Ex Machina", "Sicario"
]
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  if (currentArray.length <= 5) {
    currentArray = [];
  }
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "0: { code: 'english_movies', name: 'English Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} English movies (added second huge batch).`);
} else {
  console.log("Could not find the english_movies section.");
}
