const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
"Kalidas",
"Kalava",
"Parijatham",
"Valli Thirumanam",
"Kovalan",
"Pavalakkodi",
"Srinivasa Kalyanam",
"Sathi Sulochana",
"Nandanar",
"Menaka",
"Alli Arjuna",
"Harishchandra",
"Sathi Leelavathi",
"Naveena Sarangadhara",
"Bhaktha Kuchela",
"Pathi Bhakthi",
"Chandrahasan",
"Ambikapathy",
"Chintamani",
"Balamani",
"Sundaramurthi Nayanar",
"Sevasadanam",
"Dakshayagnam",
"Nandakumar",
"Maya Machindra",
"Tenali Raman",
"Thyaga Bhoomi",
"Prahalada",
"Shanthakumar",
"Mathru Bhoomi",
"Uthama Puthiran",
"Sakunthalai",
"Bhoologa Rambai",
"Vikrama Urvashi",
"Parasuramar",
"Aryamala",
"Sabapathy",
"Ashok Kumar",
"Bhaktha Gowri",
"Kannagi",
"Manonmani",
"Bala Nagamma",
"Sivakavi",
"Mangamma Sabatham",
"Kubera Kuchela",
"Haridas",
"Jagathalaprathapan",
"Prabhavathi",
"Meera",
"Sri Valli",
"Burma Rani",
"Chitra",
"Valmiki",
"Subhadra",
"Aayiram Thalai Vaangi Apoorva Chinthamani",
"Rajakumari",
"Nam Iruvar",
"Chandralekha",
"Vedhala Ulagam",
"Gnana Soundari",
"Apoorva Sagodharargal",
"Nallathambi",
"Laila Majnu",
"Velaikaari",
"Ezhai Padum Padu",
"Manthiri Kumari",
"Marudhanaattu Ilavarasi",
"Ponmudi",
"Marmayogi",
"Sarvadhikari",
"Devaki",
"Parasakthi",
"Panam",
"Andhaman Kaidhi",
"En Thangai",
"Manam Pola Mangalyam",
"Thirumbi Paar",
"Avvaiyar",
"Poongothai",
"Malaikkallan",
"Manohara",
"Koondukkili",
"Ratha Kanneer",
"Mangaiyar Thilakam",
"Maheswari",
"Kulebagavali",
"Kalvanin Kadhali",
"Madurai Veeran",
"Alibabavum 40 Thirudargalum",
"Pennin Perumai",
"Rangoon Radha",
"Pudhaiyal",
"Ambikapathy",
"Vanangamudi",
"Chakravarthi Thirumagal",
"Uthama Puthiran",
"Sampoorna Ramayanam",
"Annaiyin Aanai",
"Bommai Kalyanam",
"Kathavarayan",
"Thanga Padhumai",
"Sabash Meena",
"Veerapandiya Kattabomman",
"Kalyana Parisu",
"Bhaaga Pirivinai",
"Naalu Veli Nilam",
"Maragatham",
"Aval Yaar",
"Amudhavalli",
"Mamiyar Mechiya Marumagal",
"President Panchatcharam",
"Sahodhari",
"Manjal Mahimai",
"Penn Kulathin Pon Vilakku",
"Sollu Thambi Sollu",
"Uzhavukkum Thozhilukkum Vandhanai Seivom",
"Deivapiravi",
"Kalathur Kannamma",
"Mannadhi Mannan",
"Raja Desingu",
"Padikkadha Medhai",
"Baghdad Thirudan",
"Kuravanji",
"Meenda Sorgam",
"Petra Manam",
"Parthiban Kanavu",
"Paavai Vilakku",
"Vidivelli",
"Adutha Veettu Penn",
"Engal Selvi",
"Ellorum Innaattu Mannar",
"Irumbu Thirai",
"Kaidhi Kannayiram",
"Kairasi",
"Kuzhandhaigal Kanda Kudiyarasu",
"Ondrupattal Undu Vazhvu",
"Pattaliyin Vetri",
"Raja Bakthi",
"Thilakam",
"Paalum Pazhamum",
"Pasamalar",
"Punar Jenmam",
"Kappalottiya Thamizhan",
"Thirudathe",
"Kumudham",
"Marutha Nattu Veeran",
"Nallavan Vazhvan",
"Panam Panthiyile",
"Sabaash Mapillai",
"Thaai Sollai Thattadhe",
"Then Nilavu",
"Yaar Paiyan",
"Kaanal Neer",
"Arasilangkumari",
"Manapanthal",
"Aalayamani",
"Bale Pandiya",
"Paarthal Pasi Theerum",
"Padithaal Mattum Podhuma",
"Nenjil Or Aalayam",
"Konjum Salangai",
"Annai",
"Thaayai Katha Thanayan",
"Senthamarai",
"Kathirundha Kangal",
"Kudumba Thalaivan",
"Nichaya Thaamboolam",
"Policekaran Magal",
"Rani Samyuktha",
"Valar Pirai",
"Veerathirumagan",
"Vadivukku Valai Kappu",
"Anandha Jodhi",
"Iruvar Ullam",
"Karpagam",
"Kulamagal Radhai",
"Naanum Oru Penn",
"Paar Magale Paar",
"Periya Idathu Penn",
"Dharmam Thalai Kaakkum",
"Ezhai Pangalan",
"Idhayathil Nee",
"Neethikku Pin Paasam",
"Koduthu Vaithaval",
"Vanambadi",
"Chittoor Rani Padmini",
"Kaanchi Thalaivan",
"Kalai Arasi",
"Panathottam",
"Parisu",
"Pen Manam",
"Nenjam Marappathillai",
"Annai Illam",
"Kadavulai Kanden"
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/2:\s*\{\s*code:\s*'tamiglish_movies',\s*name:\s*'Tamiglish Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "2: { code: 'tamiglish_movies', name: 'Tamiglish Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/2:\s*\{\s*code:\s*'tamiglish_movies',\s*name:\s*'Tamiglish Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} Tamil movies (added second batch).`);
} else {
  console.log("Could not find the tamiglish_movies section.");
}
