const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
"Katha Parayumbol",
"Mission 90 Days",
"Mulla",
"Nasrani",
"Ore Kadal",
"Paradesi",
"Romeoo",
"Soorya Kireedam",
"Speed Track",
"Vinodayathra",
"Calcutta News",
"Abraham & Lincoln",
"Cycle",
"Crazy Gopalan",
"Gulmohar",
"Innathe Chintha Vishayam",
"Kangaroo",
"Kurukshetra",
"LollyPop",
"Madampi",
"Mulla",
"Novel",
"One Way Ticket",
"Pakal Nakshatrangal",
"Parunthu",
"Positive",
"Roudram",
"Shakespeare M.A. Malayalam",
"SMS",
"Twenty:20",
"Veruthe Oru Bharya",
"Annan Thambi",
"Minnaminnikoottam",
"Aakasha Gopuram",
"Bhagyadevatha",
"Bhramaram",
"Black Dalia",
"Chemistry",
"Colors",
"Currency",
"Daddy Cool",
"Decent Parties",
"Duplicate",
"Ee Pattanathil Bhootham",
"Evidam Swargamanu",
"Gulumal",
"I G Inspector General",
"Ivar Vivahitharayal",
"Kerala Cafe",
"Loudspeaker",
"Love in Singapore",
"Makante Achan",
"Mathilukal",
"Moz & Cat",
"Neelathamara",
"Oru Black & White Kudumbam",
"Passenger",
"Patham Nilayile Theevandi",
"Puthiya Mukham",
"Robin Hood",
"Sagar Alias Jacky Reloaded",
"Samastha Keralam PO",
"Seetha Kalyanam",
"Shudharil Shudhan",
"Banaras",
"Best Actor",
"Best of Luck",
"Cocktail",
"Again Kasarkode Khaderbai",
"Apoorvaragam",
"Athmakatha",
"Canvas",
"Four Friends",
"Happy Husbands",
"In Ghost House Inn",
"Kaaryasthan",
"Kadaksham",
"Kandahar",
"Karayilekku Oru Kadal Dooram",
"Marykkundoru Kunjaadu",
"Mummy & Me",
"Nilavu",
"Oridathoru Postman",
"Orkut Oru Ormakkoottu",
"Paappi Appacha",
"Pranchiyettan & the Saint",
"Pulliman",
"Race",
"Sakudumbam Shyamala",
"Shikkar",
"The Thriller",
"Thoovalkattu",
"Tournament",
"Traffic",
"T.D. Dasan Std. VI B",
"Yugapurushan",
"Violin",
"Elsamma Enna Aankutty",
"Electra",
"Aagathan",
"Again Kasargod Khader Bhai",
"Christian Brothers",
"Khaddama",
"Makeup Man",
"City of God",
"Beautiful",
"Salt N' Pepper",
"Indian Rupee",
"Pranayam",
"Seniors",
"The Train",
"Traffic",
"Venicile Vyapari",
"Chaappa Kurishu",
"Arabeem Ottakom P. Madhavan Nairum in Oru Marubhoomikkadha",
"Ulakam Chuttum Valiban",
"Bombay March 12",
"Doctor Love",
"Janapriyan",
"Teja Bhai & Family",
"The Metro",
"Veeraputhran",
"Ordinary",
"Diamond Necklace",
"22 Female Kottayam",
"Ustad Hotel",
"Thattathin Marayathu",
"Spirit",
"Ayalum Njanum Thammil",
"Trivandrum Lodge",
"Mallu Singh",
"Run Baby Run",
"Bachelor Party",
"Chapters",
"Cobra",
"Hero",
"Husbands in Goa",
"Ivan Megharoopan",
"Karmayodha",
"Molly Aunty Rocks!",
"My Boss",
"Puthiya Theerangal",
"Shikari",
"Simhasanam",
"The King & the Commissioner",
"101 Weddings",
"Annayum Rasoolum",
"Celluloid",
"Drishyam",
"Amen",
"Left Right Left",
"North 24 Kaatham",
"Memories",
"Mumbai Police",
"ABCD: American-Born Confused Desi",
"Artist",
"Arikil Oraal",
"Daivathinte Swantham Cleetus",
"Ezhamathe Varavu",
"Geethaanjali",
"Good Bad & Ugly",
"Housefull",
"Immanuel",
"Kadal Kadannoru Mathukkutty",
"Kunjananthante Kada",
"Ladies and Gentleman",
"Lokpal",
"Nadan",
"Natholi Oru Cheriya Meenalla",
"Neelakasham Pachakadal Chuvanna Bhoomi",
"Olipporu",
"Orissa",
"Pakaram",
"Pigman",
"Players",
"Polytechnic",
"Progress Report",
"Pullipulikalum Aattinkuttiyum",
"Punyalan Agarbattis",
"Red Wine",
"Romans",
"Rose Guitarinaal",
"Shutter",
"Sound Thoma",
"Swapaanam",
"The Power of Silence",
"Tourist Home",
"Vedivazhipadu",
"Weeping Boy",
"Zachariayude Garbhinikal",
"1983",
"Balyakalasakhi",
"Bangalore Days",
"How Old Are You",
"Ohm Shanthi Oshaana",
"Om Shanti Oshana",
"7th Day",
"Apothecary",
"Avatharam",
"Homely Meals",
"Law Point",
"Munnariyippu",
"Mr. Fraud",
"Njaan",
"Onnum Mindathe",
"Ormayundo Ee Mukham"
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/8:\s*\{\s*code:\s*'malayalaglish_movies',\s*name:\s*'Malayalaglish Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  if (currentArray.length <= 5) {
    currentArray = [];
  }
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "8: { code: 'malayalaglish_movies', name: 'Malayalaglish Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/8:\s*\{\s*code:\s*'malayalaglish_movies',\s*name:\s*'Malayalaglish Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} Malayalaglish movies (added third batch).`);
} else {
  console.log("Could not find the malayalaglish_movies section.");
}
