const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
  ...[
  "10 Cloverfield Lane", "12 Angry Men", "12 Years a Slave", "127 Hours", "13 Going on 30", "21", "21 Jump Street", "22 Jump Street", "28 Days Later", "28 Weeks Later", "300", "A Beautiful Mind", "A Bug's Life", "A Clockwork Orange", "A Few Good Men", "A Quiet Place", "A Quiet Place Part II", "A Star Is Born", "A.I. Artificial Intelligence", "About Time", "Abraham Lincoln: Vampire Hunter", "Ace Ventura: Pet Detective", "Across the Spider-Verse", "After Earth", "Air", "Air Force One", "Aladdin", "Alice in Wonderland", "Alien", "Aliens", "Alien 3", "Alien Resurrection", "Alien: Covenant", "Alita: Battle Angel", "All the President's Men", "All Quiet on the Western Front", "Almost Famous", "American Beauty", "American Gangster", "American Hustle", "American Made", "American Pie", "American Psycho", "American Sniper", "Anaconda", "Anchorman: The Legend of Ron Burgundy", "Angels & Demons", "Annihilation", "Ant-Man", "Ant-Man and the Wasp", "Ant-Man and the Wasp: Quantumania", "Apollo 13", "Aquaman", "Aquaman and the Lost Kingdom", "Argo", "Armageddon", "Arrival", "Arthur Christmas", "As Good as It Gets", "Assassin's Creed", "Asteroid City", "Atlantis: The Lost Empire", "Atomic Blonde", "Avatar", "Avatar: The Way of Water", "Avengers: Age of Ultron", "Avengers: Endgame", "Avengers: Infinity War", "Back to the Future", "Back to the Future Part II", "Back to the Future Part III", "Bad Boys", "Bad Boys II", "Bad Boys for Life", "Bad Boys: Ride or Die", "Batman", "Batman Begins", "Batman Forever", "Batman Returns", "Batman v Superman: Dawn of Justice", "Batman & Robin", "Battle: Los Angeles", "Battleship", "Bee Movie", "Beetlejuice", "Beetlejuice Beetlejuice", "Before Sunrise", "Before Sunset", "Before Midnight", "Big", "Big Hero 6", "Bird Box", "Birdman", "Black Adam", "Black Hawk Down", "Black Panther", "Black Panther: Wakanda Forever", "Black Widow", "Blade", "Blade II", "Blade Trinity"
],
...[
  "Blade Runner", "Blade Runner 2049", "Blended", "Blow", "Blue Beetle", "Bohemian Rhapsody", "Bolt", "Book of Eli", "Brave", "Braveheart", "Bridge of Spies", "Bruce Almighty", "Bullet Train", "Burn After Reading", "Captain America: Civil War", "Captain America: The First Avenger", "Captain America: The Winter Soldier", "Captain Marvel", "Captain Phillips", "Cars", "Cars 2", "Cars 3", "Casino", "Casino Royale", "Cast Away", "Catch Me If You Can", "Central Intelligence", "Charlie and the Chocolate Factory", "Chef", "Chernobyl Diaries", "Children of Men", "Cinderella", "Citizen Kane", "Clash of the Titans", "Click", "Cloud Atlas", "Cloudy with a Chance of Meatballs", "Cloverfield", "Coco", "Collateral", "Coming to America", "Con Air", "Conan the Barbarian", "Constantine", "Contagion", "Cop Out", "Coraline", "Creed", "Creed II", "Creed III", "Cruella", "Cruise", "Daddy's Home", "Daddy's Home 2", "Dances with Wolves", "Dark City", "Dark Phoenix", "Date Night", "Dawn of the Planet of the Apes", "Dead Poets Society", "Deadpool", "Deadpool 2", "Deadpool & Wolverine", "Death on the Nile", "Deep Blue Sea", "Deep Impact", "Demon Slayer", "Den of Thieves", "Despicable Me", "Despicable Me 2", "Despicable Me 3", "Despicable Me 4", "Detective Pikachu", "Die Hard", "Die Hard 2", "Die Hard with a Vengeance", "Dirty Dancing", "District 9", "Divergent", "Django Unchained", "Doctor Strange", "Doctor Strange in the Multiverse of Madness", "DodgeBall", "Don't Breathe", "Don't Look Up", "Doom", "Double Jeopardy", "Dr. Dolittle", "Dracula Untold", "Drive", "Dumb and Dumber", "Dune", "Dune: Part Two", "Dunkirk", "E.T. the Extra-Terrestrial", "Edge of Tomorrow", "Edward Scissorhands", "Elf", "Elvis", "Encanto"
],
...[
  "Enemy at the Gates", "Enola Holmes", "Enola Holmes 2", "Escape Plan", "Eternals", "EuroTrip", "Everest", "Everything Everywhere All at Once", "Ex Machina", "Extraction", "Extraction 2", "Face/Off", "Fantastic Beasts and Where to Find Them", "Fantastic Beasts: The Crimes of Grindelwald", "Fantastic Beasts: The Secrets of Dumbledore", "Fantastic Four", "Fantastic Four: Rise of the Silver Surfer", "Fantastic Mr. Fox", "Fast Five", "Fast X", "Fast & Furious", "Fast & Furious 6", "Fast & Furious Presents: Hobbs & Shaw", "Ferdinand", "Ferris Bueller's Day Off", "Fight Club", "Finding Dory", "Finding Nemo", "Finch", "First Blood", "Flags of Our Fathers", "Flight", "Flubber", "Focus", "Ford v Ferrari", "Forrest Gump", "Four Brothers", "Free Guy", "Free State of Jones", "Free Willy", "Friday", "Frozen", "Frozen II", "Fury", "Fury Road", "Game Night", "Gangs of New York", "Gemini Man", "Get Out", "Ghost", "Ghost Rider", "Ghost Rider: Spirit of Vengeance", "Ghostbusters", "Ghostbusters II", "Ghostbusters: Afterlife", "Ghostbusters: Frozen Empire", "Gladiator", "Gladiator II", "Glass", "Godzilla", "Godzilla: King of the Monsters", "Godzilla vs. Kong", "Godzilla x Kong: The New Empire", "Gone Girl", "Gone in 60 Seconds", "Good Will Hunting", "Goodfellas", "Goosebumps", "Gran Torino", "Gravity", "Green Book", "Green Lantern", "Gremlins", "Guardians of the Galaxy", "Guardians of the Galaxy Vol. 2", "Guardians of the Galaxy Vol. 3", "Gulliver's Travels", "Hacksaw Ridge", "Hancock", "Happy Feet", "Happy Gilmore", "Harry Potter and the Chamber of Secrets", "Harry Potter and the Deathly Hallows – Part 1", "Harry Potter and the Deathly Hallows – Part 2", "Harry Potter and the Goblet of Fire", "Harry Potter and the Half-Blood Prince", "Harry Potter and the Order of the Phoenix", "Harry Potter and the Philosopher's Stone", "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Sorcerer's Stone", "Heat", "Hercules", "Her", "Hidden Figures", "Home Alone", "Home Alone 2: Lost in New York", "Hook", "Hotel Transylvania", "Hotel Transylvania 2"
],
...[
  "Hotel Transylvania 3: Summer Vacation", "Hotel Transylvania: Transformania", "How to Train Your Dragon", "How to Train Your Dragon 2", "How to Train Your Dragon: The Hidden World", "Hulk", "Hugo", "Hunger", "Hunter Killer", "I Am Legend", "I, Robot", "Ice Age", "Ice Age: The Meltdown", "Ice Age: Dawn of the Dinosaurs", "Ice Age: Continental Drift", "Ice Age: Collision Course", "Identity", "In Bruges", "In Time", "Inception", "Independence Day", "Independence Day: Resurgence", "Indiana Jones and the Dial of Destiny", "Indiana Jones and the Kingdom of the Crystal Skull", "Indiana Jones and the Last Crusade", "Indiana Jones and the Temple of Doom", "Indiana Jones and the Raiders of the Lost Ark", "Inside Out", "Inside Out 2", "Insidious", "Insidious: Chapter 2", "Insidious: Chapter 3", "Insidious: The Last Key", "Interstellar", "Interview with the Vampire", "Into the Storm", "Into the Wild", "Invictus", "Iron Man", "Iron Man 2", "Iron Man 3", "It", "It Chapter Two", "Jack Reacher", "Jack Reacher: Never Go Back", "Jack Ryan: Shadow Recruit", "Jack the Giant Slayer", "Jaws", "Jingle All the Way", "John Carter", "John Wick", "John Wick: Chapter 2", "John Wick: Chapter 3 – Parabellum", "John Wick: Chapter 4", "Jojo Rabbit", "Journey 2: The Mysterious Island", "Journey to the Center of the Earth", "Jumanji", "Jumanji: Welcome to the Jungle", "Jumanji: The Next Level", "Jumper", "Jungle Cruise", "Jungle Book", "Jurassic Park", "The Lost World: Jurassic Park", "Jurassic Park III", "Jurassic World", "Jurassic World: Fallen Kingdom", "Jurassic World Dominion", "Justice League", "Justice League: The Snyder Cut", "Kick-Ass", "Kick-Ass 2", "Kill Bill: Vol. 1", "Kill Bill: Vol. 2", "King Arthur", "King Kong", "King Richard", "Kingsman: The Secret Service", "Kingsman: The Golden Circle", "Knives Out", "Kung Fu Panda", "Kung Fu Panda 2", "Kung Fu Panda 3", "Kung Fu Panda 4", "La La Land", "Lady Bird", "Lara Croft: Tomb Raider", "Last Action Hero", "Law Abiding Citizen", "Leap Year", "Leave the World Behind", "Legend", "Lethal Weapon", "Lethal Weapon 2", "Lethal Weapon 3", "Lethal Weapon 4", "Life", "Life of Pi"
],
...[
  "Lightyear", "Lincoln", "Little Miss Sunshine", "Logan", "Looper", "Lord of War", "Love Actually", "Luca", "Lucy", "Mad Max", "Mad Max 2", "Mad Max Beyond Thunderdome", "Mad Max: Fury Road", "Mad Max: Furiosa", "Madagascar", "Madagascar: Escape 2 Africa", "Madagascar 3: Europe's Most Wanted", "Maleficent", "Maleficent: Mistress of Evil", "Mamma Mia!", "Mamma Mia! Here We Go Again", "Man of Steel", "Manchester by the Sea", "Mars Attacks!", "Marley & Me", "Marriage Story", "Mary Poppins", "Mary Poppins Returns", "Matilda", "Matrix", "The Matrix Reloaded", "The Matrix Revolutions", "The Matrix Resurrections", "Mean Girls", "Meet the Parents", "Meet the Fockers", "Meet the Robinsons", "Megamind", "Men in Black", "Men in Black II", "Men in Black 3", "Men in Black: International", "Memento", "Minions", "Minions: The Rise of Gru", "Minority Report", "Mission: Impossible", "Mission: Impossible 2", "Mission: Impossible III", "Mission: Impossible – Ghost Protocol", "Mission: Impossible – Rogue Nation", "Mission: Impossible – Fallout", "Mission: Impossible – Dead Reckoning", "Moana", "Monsters, Inc.", "Monsters University", "Monster House", "Moon", "Moonfall", "Mortal Kombat", "Moulin Rouge!", "Mr. & Mrs. Smith", "Mrs. Doubtfire", "Mulan", "Murder on the Orient Express", "My Big Fat Greek Wedding", "My Big Fat Greek Wedding 2", "National Treasure", "National Treasure: Book of Secrets", "Neighbors", "Night at the Museum", "Night at the Museum: Battle of the Smithsonian", "Night at the Museum: Secret of the Tomb", "Nightcrawler", "No Country for Old Men", "No Hard Feelings", "No Time to Die", "Noah", "Nobody", "Nomadland", "Non-Stop", "Nope", "Notting Hill", "Now You See Me", "Now You See Me 2", "Oblivion", "Ocean's Eleven", "Ocean's Twelve", "Ocean's Thirteen", "Ocean's 8", "Office Space", "Old", "Olympus Has Fallen", "Once Upon a Time in America", "Once Upon a Time in Hollywood", "Onward", "Open Season", "Open Season 2", "Open Season 3"
],
...[
  "Oppenheimer", "Orphan", "Orphan: First Kill", "Oz the Great and Powerful", "Pacific Rim", "Pacific Rim: Uprising", "Paddington", "Paddington 2", "Pain & Gain", "Pan", "Pan's Labyrinth", "Panic Room", "Parasite", "Passengers", "Paul", "Pearl Harbor", "Percy Jackson & the Olympians: The Lightning Thief", "Percy Jackson: Sea of Monsters", "Pet Sematary", "Peter Pan", "Pitch Black", "Pitch Perfect", "Pitch Perfect 2", "Pitch Perfect 3", "Pixels", "Pirates of the Caribbean: The Curse of the Black Pearl", "Pirates of the Caribbean: Dead Man's Chest", "Pirates of the Caribbean: At World's End", "Pirates of the Caribbean: On Stranger Tides", "Pirates of the Caribbean: Dead Men Tell No Tales", "Planes", "Planes: Fire & Rescue", "Planet of the Apes", "Platoon", "Pocahontas", "Point Break", "Pokemon Detective Pikachu", "Polar Express", "Poltergeist", "Pompeii", "Ponyo", "Poseidon", "Power Rangers", "Predator", "Predator 2", "Predators", "Prey", "Pretty Woman", "Primal Fear", "Prince of Persia: The Sands of Time", "Prisoners", "Prometheus", "Pulp Fiction", "Purple Hearts", "Puss in Boots", "Puss in Boots: The Last Wish", "Quantum of Solace", "Raging Bull", "Ralph Breaks the Internet", "Rampage", "Rango", "Ready Player One", "Real Steel", "Rear Window", "Rebel Moon – Part One: A Child of Fire", "Rebel Moon – Part Two: The Scargiver", "Red", "Red 2", "Red Notice", "Remember the Titans", "Renfield", "Reservoir Dogs", "Resident Evil", "Resident Evil: Apocalypse", "Resident Evil: Extinction", "Resident Evil: Afterlife", "Resident Evil: Retribution", "Resident Evil: The Final Chapter", "Rio", "Rio 2", "Rise of the Guardians", "Rise of the Planet of the Apes", "Road House", "Robin Hood", "RoboCop", "Rocky", "Rocky II", "Rocky III", "Rocky IV", "Rocky V", "Rocky Balboa", "Rogue One: A Star Wars Story", "Roma", "Romancing the Stone", "Room", "Rush", "Rush Hour", "Rush Hour 2", "Rush Hour 3"
],
...[
  "Safe House", "Salt", "San Andreas", "Saving Private Ryan", "Saw", "Saw II", "Saw III", "Saw IV", "Saw V", "Saw VI", "Saw 3D", "Saw X", "Scarface", "Scary Movie", "Scary Movie 2", "Scary Movie 3", "Scary Movie 4", "Scary Movie 5", "Schindler's List", "Scoob!", "Scooby-Doo", "Scooby-Doo 2: Monsters Unleashed", "Scream", "Scream 2", "Scream 3", "Scream 4", "Scream", "Scream VI", "Se7en", "Secret Window", "Serenity", "Shang-Chi and the Legend of the Ten Rings", "Shark Tale", "Shaun of the Dead", "Sherlock Holmes", "Sherlock Holmes: A Game of Shadows", "Shrek", "Shrek 2", "Shrek the Third", "Shrek Forever After", "Shutter Island", "Sicario", "Sicario: Day of the Soldado", "Sing", "Sing 2", "Sin City", "Singin' in the Rain", "Skyfall", "Sleepy Hollow", "Smile", "Snow White and the Huntsman", "Snowpiercer", "Solo: A Star Wars Story", "Sonic the Hedgehog", "Sonic the Hedgehog 2", "Sonic the Hedgehog 3", "Soul", "Source Code", "Southpaw", "Space Jam", "Space Jam: A New Legacy", "Speed", "Speed 2: Cruise Control", "Spider-Man", "Spider-Man 2", "Spider-Man 3", "Spider-Man: Homecoming", "Spider-Man: Far From Home", "Spider-Man: No Way Home", "Spider-Man: Into the Spider-Verse", "Spider-Man: Across the Spider-Verse", "Spider-Man: Beyond the Spider-Verse", "Spirited Away", "Split", "Spy", "Spy Kids", "Spy Kids 2: The Island of Lost Dreams", "Spy Kids 3-D: Game Over", "Spy Kids: All the Time in the World", "Star Trek", "Star Trek Into Darkness", "Star Trek Beyond", "Star Wars", "Star Wars: Episode I – The Phantom Menace", "Star Wars: Episode II – Attack of the Clones", "Star Wars: Episode III – Revenge of the Sith", "Star Wars: Episode IV – A New Hope", "Star Wars: Episode V – The Empire Strikes Back", "Star Wars: Episode VI – Return of the Jedi", "Star Wars: Episode VII – The Force Awakens", "Star Wars: Episode VIII – The Last Jedi", "Star Wars: Episode IX – The Rise of Skywalker", "Stealth", "Step Brothers", "Stuart Little", "Stuart Little 2", "Sully", "Super 8"
],
...[
  "Superbad", "Superman", "Superman II", "Superman III", "Superman IV: The Quest for Peace", "Superman Returns", "Superman", "Superman: The Movie", "Superman: Legacy", "Sweeney Todd: The Demon Barber of Fleet Street", "Taken", "Taken 2", "Taken 3", "Talladega Nights: The Ballad of Ricky Bobby", "Tangled", "Tarzan", "Taxi Driver", "Ted", "Ted 2", "Teenage Mutant Ninja Turtles", "Teenage Mutant Ninja Turtles: Out of the Shadows", "Tenet", "Terminator", "Terminator 2: Judgment Day", "Terminator 3: Rise of the Machines", "Terminator Salvation", "Terminator Genisys", "Terminator: Dark Fate", "The Accountant", "The Adam Project", "The Addams Family", "The Adventures of Tintin", "The Amazing Spider-Man", "The Amazing Spider-Man 2", "The Angry Birds Movie", "The Angry Birds Movie 2", "The Ant Bully", "The Avengers", "The Bad Guys", "The Bank Job", "The Batman", "The Beach", "The Big Lebowski", "The Big Short", "The Blind Side", "The Book of Boba Fett", "The Boss Baby", "The Boss Baby: Family Business", "The Bourne Identity", "The Bourne Supremacy", "The Bourne Ultimatum", "The Bourne Legacy", "Jason Bourne", "The Breakfast Club", "The Cable Guy", "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", "The Chronicles of Narnia: Prince Caspian", "The Chronicles of Narnia: The Voyage of the Dawn Treader", "The Chronicles of Riddick", "The Conjuring", "The Conjuring 2", "The Conjuring: The Devil Made Me Do It", "The Croods", "The Croods: A New Age", "The Curious Case of Benjamin Button", "The Dark Knight", "The Dark Knight Rises", "The Da Vinci Code", "The Day After Tomorrow", "The Departed", "The Devil Wears Prada", "The Dictator", "The Equalizer", "The Equalizer 2", "The Equalizer 3", "The Exorcist", "The Exorcist: Believer", "The Expendables", "The Expendables 2", "The Expendables 3", "Expend4bles", "The Fall Guy", "The Fault in Our Stars", "The Fifth Element", "The Fighter", "The Flash", "The Fly", "The Forever Purge", "The Founder", "The French Dispatch", "The Fugitive", "The Garfield Movie", "The Gentlemen", "The Giver", "The Godfather", "The Godfather Part II", "The Godfather Part III"
],
...[
  "The Good Dinosaur", "The Good Shepherd", "The Goonies", "The Grand Budapest Hotel", "The Great Escape", "The Great Gatsby", "The Greatest Showman", "The Green Mile", "The Grey", "The Grinch", "The Hangover", "The Hangover Part II", "The Hangover Part III", "The Happening", "The Hateful Eight", "The Help", "The Hobbit: An Unexpected Journey", "The Hobbit: The Desolation of Smaug", "The Hobbit: The Battle of the Five Armies", "The Holiday", "The Hunger Games", "The Hunger Games: Catching Fire", "The Hunger Games: Mockingjay – Part 1", "The Hunger Games: Mockingjay – Part 2", "The Hunger Games: The Ballad of Songbirds & Snakes", "The Hurt Locker", "The Ice Road", "The Imitation Game", "The Incredible Hulk", "The Incredibles", "The Incredibles 2", "The Internship", "The Invisible Man", "The Irishman", "The Iron Giant", "The Jungle Book", "The Karate Kid", "The Karate Kid Part II", "The Karate Kid Part III", "The Karate Kid", "The Kid", "The King's Speech", "The Last Samurai", "The Last Airbender", "The Last Duel", "The Last Witch Hunter", "The Lego Batman Movie", "The Lego Movie", "The Lego Movie 2: The Second Part", "The Lion King", "The Lion King II: Simba's Pride", "The Little Mermaid", "The Little Things", "The Longest Yard", "The Lorax", "The Lost City", "The Lovely Bones", "The Magnificent Seven", "The Man from U.N.C.L.E.", "The Martian", "The Mask", "The Maze Runner", "The Meg", "The Meg 2: The Trench", "The Menu", "The Mist", "The Mitchells vs. the Machines", "The Mummy", "The Mummy Returns", "The Mummy: Tomb of the Dragon Emperor", "The Nice Guys", "The Nightmare Before Christmas", "The Notebook", "The Nun", "The Nun II", "The Nut Job", "The Nut Job 2: Nutty by Nature", "The Other Guys", "The Others", "The Pacifier", "The Patriot", "The Peanut Butter Falcon", "The Peanuts Movie", "The Perfect Storm", "The Perks of Being a Wallflower", "The Pianist", "The Pink Panther", "The Pink Panther 2", "The Polar Express", "The Post", "The Prestige", "The Prince of Egypt", "The Princess Bride", "The Princess Diaries", "The Princess Diaries 2: Royal Engagement", "The Proposal", "The Pursuit of Happyness", "The Purge", "The Purge: Anarchy", "The Purge: Election Year"
]
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  if (currentArray.length <= 5) {
    currentArray = [];
  }
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "0: { code: 'english_movies', name: 'English Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/0:\s*\{\s*code:\s*'english_movies',\s*name:\s*'English Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} English movies.`);
} else {
  console.log("Could not find the english_movies section.");
}
