const fs = require('fs');
const path = require('path');

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const newBatch = [
"History of Joy",
"Hadiya",
"Ivan Yarendru Therikiratha",
"Jomonte Suvisheshangal",
"Kaattu",
"Lakshyam",
"LavaKusha",
"Masterpiece",
"Match Box",
"Munthirivallikal Thalirkkumbol",
"My Story",
"Oru Cinemakkaran",
"Oru Mexican Aparatha",
"Parava",
"Paippin Chuvattile Pranayam",
"Pokkiri Simon",
"Pullikkaran Staraa",
"Punyalan Private Limited",
"Pyppin Chuvattile Pranayam",
"Queen",
"Rakshadhikari Baiju Oppu",
"Ramaleela",
"Role Models",
"Sunday Holiday",
"Take Off",
"The Great Father",
"Theeram",
"Thrissivaperoor Kliptham",
"Tiyaan",
"Udaharanam Sujatha",
"Varnyathil Aashanka",
"Velipadinte Pusthakam",
"Vimanam",
"Aami",
"Aadhi",
"Abrahaminte Santhathikal",
"Aravindante Athidhikal",
"Captain",
"Carbon",
"Chanakyathanthram",
"Contessa",
"Drama",
"Ente Mezhuthiri Athazhangal",
"Hey Jude",
"Iblis",
"Joseph",
"Kayamkulam Kochunni",
"Kinavalli",
"Koode",
"Kuttanadan Marpappa",
"Lilli",
"Love Action Drama",
"Maradona",
"Mohanlal",
"My Story",
"Njan Prakashan",
"Odiyan",
"Oru Adaar Love",
"Pathinettam Padi",
"Pretham 2",
"Queen",
"Rosapoo",
"Shikkari Shambhu",
"Sudani from Nigeria",
"Swathanthryam Ardharathriyil",
"Theevandi",
"Uncle",
"Varathan",
"Arjenteena Fans Kaattoorkadavu",
"Allu Ramendran",
"Ambili",
"And the Oscar Goes To...",
"Android Kunjappan Version 5.25",
"Athiran",
"Brother's Day",
"Children's Park",
"Finals",
"Ganagandharvan",
"Helen",
"Ishq",
"Jack & Daniel",
"Kakshi: Amminippilla",
"Kettiyollaanu Ente Malakha",
"Kumbalangi Nights",
"Love Action Drama",
"Lucifer",
"Mamangam",
"Manoharam",
"Margamkali",
"Moothon",
"My Santa",
"Pathinettam Padi",
"Porinju Mariam Jose",
"Thanneer Mathan Dinangal",
"Unda",
"Uyare",
"Virus",
"Anjaam Pathiraa",
"Ayyappanum Koshiyum",
"Trance",
"C U Soon",
"Halal Love Story",
"Kilometers and Kilometers",
"Soorarai Pottru (Malayalam Dub)",
"Maniyarayile Ashokan",
"Forensic",
"Love",
"Varthamanam",
"The Priest",
"Operation Java",
"Joji",
"Nayattu",
"Malik",
"Kuruthi",
"Minnal Murali",
"Home",
"Thinkalazhcha Nishchayam",
"Kanakam Kaamini Kalaham",
"Cold Case",
"One",
"Kala",
"Churuli",
"Star",
"Kurup",
"Sunny",
"Bhramam",
"Jan-e-Man",
"Ellam Sheriyakum",
"Madhuram",
"Member Rameshan 9am Ward",
"Upacharapoorvam Gunda Jayan",
"Kho Kho",
"Hridayam",
"Bheeshma Parvam",
"Pada",
"Salute",
"Naradan",
"CBI 5: The Brain",
"12th Man",
"John Luther",
"Malayankunju",
"Vaashi",
"Nna Thaan Case Kodu",
"Kaduva",
"Puzhu",
"Rorschach",
"Ottu",
"Pathonpatham Noottandu",
"Saturday Night",
"Gold",
"Jaya Jaya Jaya Jaya Hey",
"Appan",
"Saudi Vellakka",
"Mukundan Unni Associates",
"Ela Veezha Poonchira",
"Dear Friend",
"Super Sharanya",
"Four",
"Solamante Theneechakal",
"Keedam",
"Oruthee",
"Mahaveeryar",
"19(1)(a)",
"King Fish",
"Two Men",
"Vellaripattanam",
"Romancham",
"Nanpakal Nerathu Mayakkam",
"Pachuvum Athbutha Vilakkum",
"Christopher",
"Iratta",
"Ennalum Ente Aliya",
"Pranaya Vilasam",
"Poovan",
"Rekha",
"Corona Papers",
"Neelavelicham",
"Thrishanku",
"2018",
"Madanolsavam",
"Charles Enterprises",
"Ntikkakkakkoru Premondarnn",
"Live",
"Kannur Squad",
"RDX: Robert Dony Xavier",
"King of Kotha",
"Garudan",
"Voice of Sathyanathan",
"Journey of Love 18+",
"Kasargold",
"Padmini",
"Jaladhara Pumpset Since 1962",
"Pulimada",
"Neru",
"Abraham Ozler",
"Anweshippin Kandethum",
"Aadujeevitham"
];

const cleanedBatch = newBatch.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  return s;
}).filter(s => s.length > 0);

const match = content.match(/8:\s*\{\s*code:\s*'malayalaglish_movies',\s*name:\s*'Malayalaglish Movies',\s*words:\s*(\[.*?\])\s*\}/s);
if (match) {
  let currentArray = eval(match[1]);
  if (currentArray.length <= 5) {
    currentArray = [];
  }
  const combined = [...currentArray, ...cleanedBatch];
  const deduped = Array.from(new Set(combined));
  
  const replacement = "8: { code: 'malayalaglish_movies', name: 'Malayalaglish Movies', words: " + JSON.stringify(deduped) + " },";
  content = content.replace(/8:\s*\{\s*code:\s*'malayalaglish_movies',\s*name:\s*'Malayalaglish Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);
  fs.writeFileSync(wbPath, content);
  console.log(`Updated wordBanks.js with ${deduped.length} Malayalaglish movies (added fifth batch).`);
} else {
  console.log("Could not find the malayalaglish_movies section.");
}
