const fs = require('fs');
const path = require('path');

const raw = [
  ...[
  "10th Class", "100% Love", "118", "143 (I Miss You)", "180", "1940 Lo Oka Gramam", "3 Monkeys", "47 Days", "777 Charlie", "A Film by Aravind", "A Aa", "A1 Express", "Aa Naluguru", "Aadavari Matalaku Ardhalu Verule", "Aadi", "Aagadu", "Aakasa Ramanna", "Aakhari Poratam", "Aaradugula Bullet", "Aaro Pranam", "Aata", "Abbayitho Ammayi", "Abhilasha", "Adavi Ramudu", "Adhinayakudu", "Aditya 369", "Adrushtam", "Aggi Ramudu", "Agnyaathavaasi", "Ahana Pellanta", "Aithe", "Aithe 2.0", "Akhanda", "Akhil", "Akhil: The Power of Jua", "Akasa Veedhilo", "Ala Vaikunthapurramuloo", "Allari", "Allari Bullodu", "Allari Mogudu", "Allari Pidugu", "Allari Priyudu", "Alludu Adhurs", "Alludu Majaka", "Alludu Seenu", "Alludugaaru", "Amaran", "Ame", "Amigos", "Ammayi Bagundi", "Ammoru", "Anaganaga Oka Roju", "Anand", "Anandam", "Andala Rakshasi", "Andarivaadu", "Andagadu", "Anji", "Annamayya", "Annapurna Photo Studio", "Annavaram", "Anni Manchi Sakunamule", "Anshu", "Anthahpuram", "Antham", "Anukokunda Oka Roju", "Anukshanam", "Anveshana", "Anveshi", "Appatlo Okadundevadu", "Aravinda Sametha Veera Raghava", "Arjun", "Arjun Reddy", "Arya", "Arya 2", "Ashoka Vanamlo Arjuna Kalyanam", "Ashta Chamma", "Aswathama", "Athadu", "Athanokkade", "Athidhi", "Attarintiki Daredi", "Auto Driver", "Auto Nagar Surya", "Avakai Biryani", "Avunu", "Avunu 2", "Awe!", "Aunanna Kaadanna", "Azad", "Baadshah", "Baahubali: The Beginning", "Baahubali 2: The Conclusion", "Babu Bangaram", "Bachi", "Badri", "Balagam", "Balu", "Bangarraju", "Bangaru Bullodu"
],
...[
  "Bangaru Kodipetta", "Bangaru Kutumbam", "Bava", "Bejawada", "Bhadra", "Bhadram Be Careful Brotheru", "Bhairava Dweepam", "Bhale Bhale Magadivoy", "Bhale Dongalu", "Bhale Manchi Roju", "Bhale Mogudu", "Bhanam", "Bharat Ane Nenu", "Bheemavaram Bullodu", "Bheemla Nayak", "Bichagadu", "Big Boss", "Billa", "Bindaas", "Blade Babji", "Bobbili Raja", "Bobbili Simham", "Bommarillu", "Boss", "Boss Engira Bhaskaran", "Brahmotsavam", "Bro", "Brindavanam", "Bujjigadu", "Bunny", "Businessman", "Captain Miller", "Chakram", "Challenge", "Chalo", "Chandamama", "Chantabbai", "Chatrapathi", "Cheekati Rajyam", "Cheli", "Chenna Kesava Reddy", "Chi La Sow", "Chinnabbayi", "Chinnadana Nee Kosam", "Chintakayala Ravi", "Chirunavvutho", "Chirutha", "Chitralahari", "Choosi Choodangaane", "Choodalani Vundi", "Cinema Bandi", "Cinema Choopistha Mava", "Color Photo", "College Kumar", "Crack", "Criminal", "Current", "Current Theega", "Custody", "Daddy", "Daagudumootha Dandakor", "Damarukam", "Danger", "Darling", "Daruvu", "Das Ka Dhamki", "Dasara", "Dear Comrade", "Devadas", "Devadasu", "Devullu", "Dhamaka", "Dhammu", "Dhee", "Dikkulu Choodaku Ramayya", "DJ: Duvvada Jagannadham", "Dochay", "Donga", "Donga Dongadi", "Dongala Mutha", "Dongata", "Don Seenu", "Double iSmart", "Dorasaani", "Drushyam", "Drushyam 2", "Dubai Seenu", "Eagle", "Ee Nagaraniki Emaindi", "Eega", "Ek Niranjan", "Ela Cheppanu", "Endukante Premanta", "Entha Manchivaadavuraa", "Errabus", "Evadi Gola Vaadidhi", "Evaru", "Express Raja", "F2: Fun and Frustration", "F3: Fun and Frustration", "Family Star"
],
...[
  "Gaayam", "Gaali Sampath", "Gabbar Singh", "Gaddalakonda Ganesh", "Gaganam", "Game Changer", "Game", "Gamyam", "Gang Leader", "Gangotri", "Gentleman", "Geetha Govindam", "Geethanjali", "Geethanjali Malli Vachindi", "Ghost", "Ginna", "Godavari", "GodFather", "Golconda High School", "Golkonda High School", "Golimaar", "Gopala Gopala", "Gopi Gopika Godavari", "Gopi Goda Meeda Pilli", "Gopichand", "Gorintaku", "Goutham Nanda", "Govindudu Andarivadele", "Greeku Veerudu", "Gruham", "Gudumba Shankar", "Gulebakavali Katha", "Guna 369", "Gundamma Katha", "Happy", "Happy Days", "Hari Hara Veera Mallu", "Hello", "Hello Brother", "Hello Guru Prema Kosame", "Hero", "Hit: The First Case", "HIT: The Second Case", "HIT: The Third Case", "Hitler", "House Arrest", "Hushaaru", "Hyderabad Nawabs", "Iddarammayilatho", "Iddaru Mitrulu", "Iddari Lokam Okate", "Idiot", "Indra", "Indrudu", "Intelligent", "Intlo Ramayya Veedhilo Krishnayya", "Itlu Maredumilli Prajaneekam", "Itlu Sravani Subramanyam", "iSmart Shankar", "Ishq", "Jagadam", "Jagadeka Veerudu Athiloka Sundari", "Jai Chiranjeeva", "Jalsa", "Jambalakidi Pamba", "James Bond", "Janatha Garage", "Jayam", "Jebu Donga", "Jersey", "Jessie", "Jil", "Johnny", "Joru", "Journey", "Julayi", "Kalki", "Kalki 2898 AD", "Kalisundam Raa", "Kalyana Ramudu", "Kalyanam Kamaneeyam", "Kanche", "Kandireega", "Kantri", "Karthikeya", "Karthikeya 2", "Kedi", "Kerintha", "Keshava", "Khadgam", "Khaidi", "Khaidi No. 786", "Khaidi No. 150", "Khaleja", "King", "Kirayi Rowdylu", "Kick", "Kick 2", "Kittu Unnadu Jagratha", "Kodama Simham"
],
...[
  "Kodanda Ramudu", "Koduku Diddina Kapuram", "Komaram Puli", "Konchem Ishtam Konchem Kashtam", "Kondapolam", "Kondaveeti Donga", "Kondaveeti Raja", "Kotha Bangaru Lokam", "Kotha Janta", "Kousalya Krishnamurthy", "Krack", "Krishna", "Krishna Gaadi Veera Prema Gaadha", "Krishna Babu", "Krishnam Vande Jagadgurum", "Kshana Kshanam", "Kshanam", "Kshatriya Putrudu", "Kshudra", "Kushi", "Lakshmi", "Lakshyam", "Leader", "Legend", "Ladies Tailor", "Lawyer Suhasini", "Lie", "Life Is Beautiful", "Lion", "Love Story", "Lovely", "Loukyam", "Lorry Driver", "Lucky Baskhar", "Maa Annayya", "Maa Aavida Meeda Ottu Mee Aavida Chala Manchidi", "Maa Nanna Superhero", "Maa Oori Polimera", "Maa Oori Polimera 2", "Madhumasam", "Mad", "Magadheera", "Maharadhi", "Mahanandi", "Mahanati", "Maharshi", "Mahasamudram", "Major", "Malliswari", "Mallesham", "Malli Malli Idi Rani Roju", "Malli Raava", "Manam", "Manasantha Nuvve", "Manchi Donga", "Manchi Manasulu", "Manchi Rojulochaie", "Manmadhudu", "Manmadhudu 2", "Mangalavaaram", "Mangamma Gari Manavadu", "Maro Charitra", "Maryada Ramanna", "Mass", "Maska", "Master", "Mathu Vadalara", "Mathu Vadalara 2", "Mayabazar", "Mechanic Alludu", "Mechanic Rocky", "Meda Meeda Abbayi", "Mem Famous", "Middle Class Abbayi", "Midhunam", "Mirapakay", "Mirchi", "Miss Shetty Mr Polishetty", "Mister", "Mister Pellam", "Money", "Money Money", "Mosagallu", "Mr. Majnu", "Mr. Perfect", "Muddula Mavayya", "Mugguru Monagallu", "Mukunda", "Murari", "Muta Mesthri", "Muvva Gopaludu", "Mythri", "Naa Alludu", "Naa Autograph", "Naa Ishtam", "Naa Peru Surya", "Naandhi", "Naayak", "Nagavalli", "Nani"
],
...[
  "Nannaku Prematho", "Narappa", "Narasimha Naidu", "Nari Nari Naduma Murari", "Nava Vasantham", "Nava Manmadhudu", "Nee Sneham", "Needi Naadi Oke Katha", "Neeve", "Neevevaro", "Neninthe", "Nenu", "Nenu Local", "Nenu Meeku Telusa...?", "Nenu Sailaja", "Neramu Siksha", "Nijam", "Ninne Ishtapaddanu", "Ninne Pelladata", "Ninne Premistha", "Ninnila Ninnila", "Ninnu Choodalani", "Ninnu Kori", "Nippu", "Nippu Ravva", "Nirnayam", "Nuvve Kavali", "Nuvve Nuvve", "Nuvvu Leka Nenu Lenu", "Nuvvu Naaku Nachav", "Nuvvu Nenu", "Nuvvu Vastavani", "Nuvvostanante Nenoddantana", "O Baby", "O Chinadana", "O Manchi Roju Choosi Chepta", "O My Friend", "Oh! Baby", "Ok Bangaram", "Oka Chinna Family Story", "Oka Laila Kosam", "Oka Oorilo", "Okariki Okaru", "Okka Kshanam", "Okkadu", "Ontari", "Operation Valentine", "Orange", "Ori Devuda", "Oosaravelli", "Oopiri", "Oohalu Gusagusalade", "Padi Padi Leche Manasu", "Paagal", "Paandavulu Paandavulu Thummeda", "Paisa", "Palasa 1978", "Pandaga Chesko", "Pandurangadu", "Panjaa", "Paper Boy", "Parugu", "Pataas", "Pedababu", "Peddannayya", "Pelli Choopulu", "Pelli Sandadi", "Pelli SandaD", "Pilla Zamindar", "Pokiri", "Police Story", "पोलीस Vari Hecharika", "Power", "Pranam", "Prasthanam", "Prema", "Prema Desam", "Prema Katha", "Prema Katha Chitram", "Prema Katha Chitram 2", "Prema Kavali", "Premabhishekam", "Premaku Velayera", "President Gari Pellam", "President Gari Abbai", "Priyamaina Neeku", "Pushpa: The Rise", "Pushpa 2: The Rule", "Raarandoi Veduka Chudham", "Racha", "Radha", "Radhe Shyam", "Ragada", "Raja", "Raja The Great", "Rajanna", "Rakhi", "Rakshakudu"
],
...[
  "Rakshasudu", "Rakta Charitra", "Rakta Charitra 2", "Rakta Sindhuram", "Ramabanam", "Rambantu", "Ramudochadu", "Ramayya Vasthavayya", "Rang De", "Rangasthalam", "Raraju", "Ravanasura", "Ravoyi Chandamama", "Ready", "Republic", "Ride", "Robinhood", "Roberrt", "Robo", "Romantic", "Rowdy Alludu", "Rowdy Fellow", "Rowdy Inspector", "Rudhramadevi", "Rudraveena", "Run", "Run Raja Run", "Saahasam", "Sahasam", "Sainikudu", "Sakhi", "Salaam Hyderabad", "Samarasimha Reddy", "Sammohanam", "Sankarabharanam", "Sankranthiki Vasthunnam", "Santosham", "Sapthagiri Express", "Sapthagiri LLB", "Saradaga Kasepu", "Sarocharu", "Sarileru Neekevvaru", "Sarkaru Vaari Paata", "Sarrainodu", "Sasirekha Parinayam", "Satamanam Bhavati", "Seema Simham", "Seethamma Vakitlo Sirimalle Chettu", "Seetharama Kalyanam", "Seetharamayya Gari Manavaralu", "Sehari", "Selfie Raja", "Shailaja Reddy Alludu", "Shakti", "Shambo Shiva Shambo", "Shankar Dada MBBS", "Shankar Dada Zindabad", "Shankara", "Shankham", "Shatamanam Bhavati", "Sher", "Shirdi Sai", "Shiva", "Shivamani", "Shourya", "Shyam Singha Roy", "Simha", "Simhadri", "Sindhooram", "Sindhooram (2023)", "Sir", "Sita Ramam", "Sivaji", "Skanda", "Soggade Chinni Nayana", "Solo", "Sontham", "Son of India", "Sowbhagyam", "Spy", "Spyder", "Sri", "Srirastu Subhamastu", "Sri Ramadasu", "Srinivasa Kalyanam", "Srimanthudu", "State Rowdy", "Stalin", "Student No.1", "Subash Chandra Bose", "Subhalagnam", "Subhapradam", "Subramanyam for Sale", "Sudigadu", "Sultan", "Super", "Super Machi", "Surya vs Surya", "Suswagatham", "Swag", "Swamy Ra Ra", "Swarna Kamalam", "Sye"
],
...[
  "Tagore", "Takkari", "Takkari Donga", "Takkari Pellam", "Tandel", "Tata Birla Madhyalo Laila", "Taxiwaala", "Temper", "Thank You", "Thammudu", "The Ghost", "The Raja Saab", "Tholi Prema", "Tholi Prema (1998)", "Thotti Gang", "Tiger", "Tikka", "Tillu Square", "Tirumala Tirupati Venkatesa", "Todu Dongalu", "Top Hero", "Tulasi", "Tuck Jagadish", "Tuneega Tuneega", "Ugram", "Ullasamga Utsahamga", "Undamma Bottu Pedata", "Undi Porade", "Uu Kodathara? Ulikki Padathara?", "Uyyala Jampala", "V", "Vaana", "Vaarasudochadu", "Vakeel Saab", "Valmiki", "Vamshi", "Vamsanikokkadu", "Varasudu", "Varsham", "Varudu", "Vasantham", "Vedam", "Veede", "Veedokkade", "Veera", "Veera Simha Reddy", "Venkatadri Express", "Venky", "Venky Mama", "Victory", "Vijayendra Varma", "Vikramarkudu", "Village Lo Vinayakudu", "Vinaro Bhagyamu Vishnu Katha", "Vinaya Vidheya Rama", "Virajaji", "Virodhi", "Virupaksha", "Virata Parvam", "Vishnu", "Vishwambhara", "Viyyalavari Kayyalu", "Wanted", "Waltair Veerayya", "Yagnam", "Yamadonga", "Yamaleela", "Yamudiki Mogudu", "Yatra", "Yatra 2", "Ye Maaya Chesave", "Yevade Subramanyam", "Yevadu", "Yogi", "Yuganiki Okkadu", "Yuvaraju", "Yuvasena", "Zombie Reddy", "Ammoru 2", "Aaradugula Bullet", "Ammayi Kosam", "Anasuya", "Ashwamedham", "Athili Sattibabu LKG", "Bava Nachadu", "Bhale Pellam", "Chanti", "Chudalani Undi", "Collector Gari Alludu", "Dongodu", "Eduruleni Manishi", "Gharana Bullodu", "Goppinti Alludu", "Jayam Manadera", "Kondaveeti Simham", "Lakshmi Narasimha", "Madhyalo Mahabharatam", "Muddula Menalludu", "Pavitra Bandham"
],
...[
  "Pavithra", "Pelli", "Pelli Kanuka", "Pelli Pandiri", "Pelli Pustakam", "Pelli Roju", "Pelli Sambandham", "Pelli Peetalu", "Pelli Chesukundam", "Pelli Koduku", "Pelli Gola", "Pelli Kani Prasad", "Pelli Neeku Shubham Naaku Labham", "Pelliam Oorelithe", "Pelliam Chebite Vinali", "Pelliam Oorelithe 2", "Pellamto Panenti", "Pellaniki Premalekha Priyuraliki Subhalekha", "Pellam Oorelithe", "Pellam Picchodu", "Pellam Uppena", "Pellaina Kothalo", "Pellam Chebite Vinali", "Pellivaramandi", "Pelli Sandadi (1996)", "Pelli SandaD (2021)", "Pelli Pustakam", "Pellam Oorelithe", "People's Encounter", "Pilla Nuvvu Leni Jeevitham", "Pilla Zamindar", "Pitta Kathalu", "Pittala Dora", "Police Bharya", "Police Brothers", "Police Lockup", "Police Police", "Police Story 2", "Police Vari Hecharika", "Political Rowdy", "Poola Rangadu", "पोతురాజు", "पोరాటం", "पोరాటం లోకం", "पोరుగింటి పుల్లకూర", "पोతుగాడు", "पोతినేని", "पोరంబోకు", "पोరాట వీరుడు", "पोస్ట్మాన్", "पोట్టేలు పున్నమ్మ", "Pratighatana", "Prayanam", "Prema & Co.", "Prema Entha Madhuram", "Prema Ichukundam Raa", "Prema Lekha", "Prema Mandiram", "Prema Nagar", "Prema Oka Maikam", "Prema Pipasi", "Premabhishekam", "Premante Idera", "Premante Inthe", "Premikudu", "Premikula Roju", "Preminchu", "Premiste", "Priyamaina Srivaru", "Priyamudan", "Priyamyna Neeku", "Punyabhumi Naa Desam", "Puttintiki Ra Chelli", "Puttinillu Mettinillu", "Qaidi Dada", "Queen", "Raa", "Raa Raa", "Raaj", "Raajugari Ammayi Nayudu gari Abbayi", "Raajugari Gadhi", "Raajugari Gadhi 2", "Raajugari Gadhi 3", "Raam", "Rabhasa", "Radha Gopalam", "Raghavendra", "Railway Coolie", "Rajendrudu Gajendrudu", "Rajugadu", "Raju Gari Gadhi", "Raju Gari Gadhi 2", "Raju Gari Gadhi 3", "Raju Maharaju", "Raju Yadav", "Raktha Tilakam", "Raktha Sambandham", "Rama Rama Krishna Krishna", "Ramaraju", "Ramulamma"
]
];

const cleaned = raw.map(name => {
  let s = name.replace(/[^a-zA-Z0-9\s]/g, ' ');
  s = s.replace(/\s+/g, ' ').trim().toLowerCase();
  
  if (s === 'aithe 2 0') s = 'aithe 2'; 
  
  return s;
}).filter(s => s.length > 0);

const deduped = Array.from(new Set(cleaned));

const wbPath = path.join(__dirname, 'wordBanks.js');
let content = fs.readFileSync(wbPath, 'utf8');

const replacement = "3: { code: 'teluglish_movies', name: 'Teluglish Movies', words: " + JSON.stringify(deduped) + " },";

content = content.replace(/3:\s*\{\s*code:\s*'teluglish_movies',\s*name:\s*'Teluglish Movies',\s*words:\s*\[.*?\]\s*\}/s, replacement);

fs.writeFileSync(wbPath, content);
console.log(`Updated wordBanks.js with ${deduped.length} Telugu movies.`);
